### ISSUE TITLE
how to use it

### ISSUE THREAD

**Issue by TimerZz007** [luca364/rust-stealer#5]
i have compiled it，but it seems does not work，i double click it，nothing hanppend...

**Comment by luca364** [comment]
Could you post a censored screenshot of your main.rs? (Config)

**Comment by TimerZz007** [comment]
i don't modify main.rs . it is the  original file . does something should be modify for it？

**Comment by luca364** [comment]
Sorry,
But you need to modify it with your tg data, or webhook so it knows where to send it 😂 
I think this can be closed.
